/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 public/models/alltogether.glb
*/

import React, { useLayoutEffect, useRef } from 'react'
import gsap from "gsap";
import { useGLTF, useScroll } from '@react-three/drei'
import { useFrame } from '@react-three/fiber';

export const PLANET_HEIGHT=2.5;
export const NB_PLANETS=8;

export function Planets(props) {
  const { nodes, materials } = useGLTF('./models/alltogether.glb')
  const ref = useRef();
  const tl = useRef();
  
  const scroll = useScroll();

  useFrame(()=>{
    tl.current.seek(scroll.offset * tl.current.duration());
  });
 
  useLayoutEffect(()=> {
    tl.current = gsap.timeline();
    // vertical animation
    tl.current.to(ref.current.position, {
        duration:2, y: -PLANET_HEIGHT * (NB_PLANETS-1),
    },
    0
    );
  }, []);

  return (
    <group {...props} dispose={null} ref={ref}>
      <mesh geometry={nodes.Bespin.geometry} material={materials['Material.001']} position={[1, 3, 0]} />
      <mesh geometry={nodes.Alderaan.geometry} material={materials['Material.001']} position={[1, 15, 0]} />
      <mesh geometry={nodes.Dagobah.geometry} material={materials['Material.002']} position={[1, 6, 0]} />
      <mesh geometry={nodes.Endor.geometry} material={materials['Material.003']} position={[1, 0, 0]} />
      <mesh geometry={nodes.Hoth.geometry} material={materials['Material.004']} position={[1, 9, 0]}/>
      <mesh geometry={nodes.YavinIV.geometry} material={materials['Material.005']} position={[1, 12, 0]} />
      <mesh geometry={nodes.tatooine.geometry} material={materials['Material.007']} position={[1, 18, 0]} />
    </group>
  )
}

useGLTF.preload('/models/alltogether.glb')
